# Stage Informatica - Data Anlysis and Intelligent System

## Introduzione

Argomenti trattati:
- Big Data
- Data sets
- Data Analysis
- Intelligent Systems

# Big Data

## Cosa sono i Big Data?
- Quantità e flusso di dati così grande e complesso che le tradizionali tecnologie (SQL) di data managment non riescono a gestire
- NoSQL databases sono emersi grazie alla loro capacità di gestire big data
    - Fondamentale riuscire ad estrarre informazioni utili e prezione
- Sistemi di intelligenza artificiale riscono a riconoscere pattern all'interno di grandi volumi di dati
    - Esempio: Identificare abitudini di:
        - Acquisto
        - Visione e ascolto
        - Interazione

## Esempi
### Amazon Shopping
**Dati**: Storico acquisti, Informazioni demografiche. <br>
**Analisi**: Potenziali acquisti. <br>
**Prodotto**: Plubbicità Ad-Hoc. <br>
### Uber
**Dati**: Storico Corse, Traffico, Richieste. <br>
**Analisi**: Picchi di domanda, Variazione della disponibilità dei driver. <br>
**Prodotto**: Aggiustamento del prezzo della corsa. <br>
### Netflix
**Dati**: Contenuti guardati, Interazione con la piattaforma. <br>
**Analisi**: Titoli preferiti, Livello di attenzione, Pattern di visualizzazione. <br>
**Prodotto**: Titotli da consigliare, Prodotto su cui investire. <br>

## Web Data Mining
Il Web è la più grande sorgente di informazione pubblicamente accessibile al mondo:
- **Enorme quantità di dati**: in continua crescita, info su quasi qualunque cosa 
- **Eterogeneità del formato dei dati**: tabelle, pagine web (immagini, audio, video) 
- **Eterogeneità dell'informazione**
- **Rumore e ridondanza** → (content mining), adattabilità del contenuto 
- **Dinamico**: info cambia nel tempo → monitoraggio cambiamenti
- **Società virtuale**: forum, blog, siti di review, reti sociali → opinion mining, social network analysis

## Esempio:
**[Twitter Analysis](http://bigdata.stratebi.com)** <br>
**Problema**: Predizione gusti degli utenti. <br>
**Misura di prestazione**: Percentuale tweet correttamente analizzati. <br>
**Esperienza**: Utenti già profilati e relazioni già osservate. <br>

# Dataset
Un dataset è una collezione di dati. Nel caso di dati tabulari, un set di dati corrisponde a una o più tabelle di un database, dove ogni colonna di una tabella rappresenta una particolare variabile, e ogni riga corrisponde a un dato record del set di dati in questione.

## Risorse:
- [Google Datasets](https://research.google/tools/datasets)
- [Kaggle](https:www.kaggle.com)
    - Cometizioni:
        - Esempi di problemi reali
        - Compenso economico per il vincitore
        - Esempi:
            - [H&M](https://www.kaggle.com/c/h-and-m-personalized-fashion-recommendations)
            - [Titanic](https://www.kaggle.com/c/titanic)
            - [G-Research Crypto Forecasting](https://www.kaggle.com/c/g-research-crypto-forecasting)
            - [Feedback Prize - Evaluating Student Writing](https://www.kaggle.com/c/feedback-prize-2021)

# [Pandas](https://pandas.pydata.org) Tutorial

In [13]:
import pandas as pd

#Data Frame = 
df_ride = pd.read_csv("datasets/cab_rides.csv") #Funzione per leggere il dataset

df_shoes.head()

,id,asins,brand,categories,colors,count,dateAdded,dateUpdated,descriptions,dimension,...,prices.warranty,quantities,reviews,sizes,skus,sourceURLs,upc,vin,websiteIDs,weight
0,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,6.993020e+11,NaN,NaN,NaN
1,AVpfHrJ6ilAPnD_xVXOI,NaN,Josmo,"Clothing,Shoes,Men's Shoes,All Men's Shoes",NaN,NaN,2016-11-07T00:45:12Z,2016-11-07T00:45:12Z,"[{""dateSeen"":[""2016-11-07T00:45:12Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,https://www.walmart.com/ip/Josmo-8190-Plain-In...,6.993020e+11,NaN,NaN,NaN
2,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
3,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN
4,AVpfHsWP1cnluZ0-eVZ7,NaN,SERVUS BY HONEYWELL,"All Men's Shoes,Shoes,Men's Shoes,Clothing",NaN,NaN,2016-06-14T04:29:57Z,2016-07-09T20:26:48Z,"[{""dateSeen"":[""2016-07-09T20:26:48Z""],""sourceU...",NaN,...,NaN,NaN,NaN,NaN,NaN,http://www.walmart.com/ip/Studs-Shoe-Large-Pr-...,NaN,NaN,NaN,NaN

In [14]:
df_ride["price"].head()

0     5.0
1    11.0
2     7.0
3    26.0
4     9.0
Name: price, dtype: float64

**Dividiamo il dataset**

In [15]:
uber_df = df_ride[ df_ride["cab_type"] == "Uber" ]
lyft_df = df_ride[ df_ride["cab_type"] == "Lyft" ]

In [17]:
uber_df.head()

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,id,product_id,name
12,1.11,Uber,1543615981179,West End,North End,12.0,1.0,009e9c53-074d-43cf-aef2-0fbc7a47ed3d,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
13,1.11,Uber,1544698211014,West End,North End,16.0,1.0,23f145da-f0c1-4d1f-a184-496bc003a7db,6c84fd89-3f11-4782-9b50-97c468b19529,Black
14,1.11,Uber,1544728503935,West End,North End,7.5,1.0,357559cb-8c58-4278-a41a-e33b2e0997a3,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
15,1.11,Uber,1545004511430,West End,North End,7.5,1.0,50ef1165-9d23-416c-a65c-18906207b295,9a0e7b09-b92b-4c41-9779-2ad22b4d779d,WAV
16,1.11,Uber,1544748007961,West End,North End,26.0,1.0,91c4861c-1780-42b0-bca1-bbd64a422cc3,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV

In [18]:
uber_df.set_index("id")

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,product_id,name
id,,,,,,,,,
009e9c53-074d-43cf-aef2-0fbc7a47ed3d,1.11,Uber,1543615981179,West End,North End,12.0,1.0,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
23f145da-f0c1-4d1f-a184-496bc003a7db,1.11,Uber,1544698211014,West End,North End,16.0,1.0,6c84fd89-3f11-4782-9b50-97c468b19529,Black
357559cb-8c58-4278-a41a-e33b2e0997a3,1.11,Uber,1544728503935,West End,North End,7.5,1.0,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
50ef1165-9d23-416c-a65c-18906207b295,1.11,Uber,1545004511430,West End,North End,7.5,1.0,9a0e7b09-b92b-4c41-9779-2ad22b4d779d,WAV
91c4861c-1780-42b0-bca1-bbd64a422cc3,1.11,Uber,1544748007961,West End,North End,26.0,1.0,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV
...,...,...,...,...,...,...,...,...,...
616d3611-1820-450a-9845-a9ff304a4842,1.00,Uber,1543708385534,North End,West End,13.0,1.0,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
633a3fc3-1f86-4b9e-9d48-2b7132112341,1.00,Uber,1543708385534,North End,West End,9.5,1.0,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
64d451d0-639f-47a4-9b7c-6fd92fbd264f,1.00,Uber,1543708385534,North End,West End,NaN,1.0,8cf7e821-f0d3-49c6-8eba-e679c0ebcf6a,Taxi
727e5f07-a96b-4ad1-a2c7-9abc3ad55b4e,1.00,Uber,1543708385534,North End,West End,27.0,1.0,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV
e7fdc087-fe86-40a5-a3c3-3b2a8badcbda,1.00,Uber,1543708385534,North End,West End,10.0,1.0,997acbb5-e102-41e1-b155-9df7de0a73f2,UberPool

In [19]:
uber_df.head()

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,id,product_id,name
12,1.11,Uber,1543615981179,West End,North End,12.0,1.0,009e9c53-074d-43cf-aef2-0fbc7a47ed3d,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
13,1.11,Uber,1544698211014,West End,North End,16.0,1.0,23f145da-f0c1-4d1f-a184-496bc003a7db,6c84fd89-3f11-4782-9b50-97c468b19529,Black
14,1.11,Uber,1544728503935,West End,North End,7.5,1.0,357559cb-8c58-4278-a41a-e33b2e0997a3,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
15,1.11,Uber,1545004511430,West End,North End,7.5,1.0,50ef1165-9d23-416c-a65c-18906207b295,9a0e7b09-b92b-4c41-9779-2ad22b4d779d,WAV
16,1.11,Uber,1544748007961,West End,North End,26.0,1.0,91c4861c-1780-42b0-bca1-bbd64a422cc3,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV

Molte operazioni in Pandas ritornano un nuovo dataset, se esso non viene ridefinito in una variabile il contenuto verrà perso

In [20]:
uber_df = uber_df.set_index("id") #inpace

In [21]:
uber_df

,distance,cab_type,time_stamp,destination,source,price,surge_multiplier,product_id,name
id,,,,,,,,,
009e9c53-074d-43cf-aef2-0fbc7a47ed3d,1.11,Uber,1543615981179,West End,North End,12.0,1.0,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
23f145da-f0c1-4d1f-a184-496bc003a7db,1.11,Uber,1544698211014,West End,North End,16.0,1.0,6c84fd89-3f11-4782-9b50-97c468b19529,Black
357559cb-8c58-4278-a41a-e33b2e0997a3,1.11,Uber,1544728503935,West End,North End,7.5,1.0,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
50ef1165-9d23-416c-a65c-18906207b295,1.11,Uber,1545004511430,West End,North End,7.5,1.0,9a0e7b09-b92b-4c41-9779-2ad22b4d779d,WAV
91c4861c-1780-42b0-bca1-bbd64a422cc3,1.11,Uber,1544748007961,West End,North End,26.0,1.0,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV
...,...,...,...,...,...,...,...,...,...
616d3611-1820-450a-9845-a9ff304a4842,1.00,Uber,1543708385534,North End,West End,13.0,1.0,6f72dfc5-27f1-42e8-84db-ccc7a75f6969,UberXL
633a3fc3-1f86-4b9e-9d48-2b7132112341,1.00,Uber,1543708385534,North End,West End,9.5,1.0,55c66225-fbe7-4fd5-9072-eab1ece5e23e,UberX
64d451d0-639f-47a4-9b7c-6fd92fbd264f,1.00,Uber,1543708385534,North End,West End,NaN,1.0,8cf7e821-f0d3-49c6-8eba-e679c0ebcf6a,Taxi
727e5f07-a96b-4ad1-a2c7-9abc3ad55b4e,1.00,Uber,1543708385534,North End,West End,27.0,1.0,6d318bcc-22a3-4af6-bddd-b409bfce1546,Black SUV
e7fdc087-fe86-40a5-a3c3-3b2a8badcbda,1.00,Uber,1543708385534,North End,West End,10.0,1.0,997acbb5-e102-41e1-b155-9df7de0a73f2,UberPool